version: '3'

services:
  app:
    container_name: app
    build: 
      context: ./node
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 5s docker-entrypoint.sh
    depends_on: 
       - db
    volumes: 
      - ./node:/usr/src/app
    networks: 
      - app-network
    
  db:
    container_name: db
    build: 
      context: ./mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes: 
      - ./mysql/volume:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    depends_on: 
      - app
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge 
